// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using xamarinIOSTask.ApplicationCore.Helper;
using xamarinIOSTask.Domain.Entity;

namespace xamarinIOSTask.Presentation.Home
{
	public partial class ReviewCell : UICollectionViewCell
	{
		UIImage _doctorImage = null;
		UIImage _patientImage = null;
		public ReviewCell (IntPtr handle) : base (handle)
		{
		}
        public void ConfigureCell(Review review)
        {
			this.Tag = review.ID;
			this.bigView.Layer.CornerRadius = 10;
			this.bigView.Layer.BorderColor = UIColor.Gray.CGColor;
			this.bigView.Layer.BorderWidth = 1;

			this.patientImage.Layer.CornerRadius = 30;
			this.patientImage.Layer.MasksToBounds = true;

			this.patientName.Text = review.PatientName;
			if(_patientImage == null)
            {
				_patientImage = _patientImage.FromUrl(review.PatientImageURL);
			}
			this.patientImage.Image = _patientImage;
			this.patientComment.Text = review.PatientComment;
			this.patientAge.Text = review.PatientAge + " Years";
			this.sinceWhen.Text = review.SinceTime;
			this.docotrImage.Layer.CornerRadius = 30;
			this.docotrImage.Layer.MasksToBounds = true;
			if (_doctorImage == null)
			{
				_doctorImage= _doctorImage.FromUrl(review.DoctorImageURL);
			}
			this.docotrImage.Image = _doctorImage;
			this.doctorName.Text = review.DoctorName;
			this.doctorSpecialize.Text = review.DoctorField;
			this.reviewsCount.Text = review.DoctorReviewsCount + " Reviews";
			this.ratingImage.Image = UIImage.FromBundle(Constants.Reviews[review.DoctorRate -1]);
        }
	}
}
